name: Publish Package

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Version
        id: version
        run: |
          VERSION=$(date +"%Y.%m.%d")-$(openssl rand -hex 3)-SNAPSHOT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish package
        run: ./gradlew publish -PprojectVersion=${{ steps.version.outputs.version }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Published version ${{ steps.version.outputs.version }}"
